# Header
menu:
  主页: https://262235.xyz/
  龙芯2F镜像: http://srgb.vicp.net/
  博客: /
  归档: /archives
  站点地图: /sitemap.xml
  GitHub: https://github.com/hongwenjun
  YouTube频道: https://www.youtube.com/sRGB18
  B站频道: https://space.bilibili.com/320303690/

#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'yearly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /logo/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
